version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev   # 👈 Dev Dockerfile with hot reload
    container_name: nest_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app              # 👈 Mount source code for live reload
      - /app/node_modules           # 👈 Keep container node_modules
    depends_on:
      - db
    command: npm run start:dev      # 👈 NestJS watch mode

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   # 👈 Dev Dockerfile for Next.js
    container_name: next_frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app            # 👈 Mount source code for hot reload
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev           # 👈 Next.js dev server

volumes:
  pgdata:
